parser:
    measurement: environment-statistics
    command: show chassis environment
    type: xml
    matches:
    -   type: multi-value
        method: xpath
        xpath: //environment-information/environment-item[temperature]
        loop:
            type: ./class
            item: ./name
            sub-matches:
            -   xpath: ./temperature/@celsius
                variable-name: temperature
           
        