version: '3'

services:
  db:
    image: influxdb:1.6.2-alpine
    environment:
      - INFLUXDB_DB=py-mc
    ports:
      - 8086:8086

  telegraf:
    image: telegraf:1.7.3-alpine
    volumes:
      - ./quickstart/telegraf.conf:/etc/telegraf/telegraf.conf
    ports:
      - 8186:8186

  metric-collector:
    build: .
    depends_on:
      - telegraf
    entrypoint:
      - metric-collector
      - --commands=commands.yaml
      - --start
      - --credentials=${CREDENTIALS:-credentials.yaml}
      - --hosts=${HOSTS:-hosts.yaml}
      - --output-type=http
      - --output-addr=http://telegraf:8186/write
      - --use-scheduler
    volumes:
      - ./quickstart:/quickstart
    working_dir: /quickstart
    ports:
      - "8000:8000"
    depends_on:
      - db

  grafana:
    image: grafana/grafana:5.1.0
    volumes:
      - ./quickstart/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./quickstart/grafana/dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - "3000:3000"

