netbox:
    main:
        api_url: 'http://<netbox_addr>/api/dcim/devices/'
        
    # Value to use as the device_type, default to (device_type/manufacturer/slug)
    # device_type: platform

    filters:
      juniper:
        - site: [aa, bb, cc]
        - manufacturer: juniper

    # What tags will be applied
    tags:
        # Default section in Netbox.
        default:
            - device_role
            - site
            - platform

        static: [tag1]

        # Custom sections (custom_fields) could be used.
        #custom:
        #    - env
    
    # Use Netbox sections as contextial information
    context:
        # Any other sections.
        general:
            platform: platform
            role: device_role
            site: site

