{
 "title": "Router Stats",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "query": "SHOW TAG VALUES  WITH KEY = \"device\" "
   }
  ]
 },
 "panels": [
  {
   "title": "$device Route Summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[device]] [[tag_key]] $col",
     "groupBy": [
      { "params": [ "key" ], "type": "tag" }
     ],
     "measurement": "jnpr_route_summary",
     "select": [
      [
       { "params": [ "actives" ], "type": "field" }
      ],
      [
       { "params": [ "destinations" ], "type": "field" }
      ],
      [
       { "params": [ "hidden" ], "type": "field" }
      ],
      [
       { "params": [ "holddown" ], "type": "field" }
      ],
      [
       { "params": [ "routes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "$device routing engine stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[device]] $col",
     "measurement": "jnpr_routing_engine",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "$device KRT Stats",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "repeat": "device",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[device]] $col",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "jnpr_krt_state",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "$device process memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_process]]",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "jnpr_system_process",
     "select": [
      [
       { "params": [ "memory" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  }
 ]
}